apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.40.0
    helm:
      values: |
        loki:
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: ""
          storage:
            type: filesystem
            filesystem:
              directory: /var/loki
          config:
            auth_enabled: false
            server:
              http_listen_port: 3100
              grpc_listen_port: 9095
          limits_config:
            enforce_metric_name: false
            reject_old_samples: true
            reject_old_samples_max_age: 168h
          schema_config:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: loki_index_
                  period: 168h
          compactor:
            working_directory: /var/loki/compactor
            shared_store: filesystem
          frontend:
            enabled: true
            log_queries_longer_than: 5s
            compress_responses: true
          query_range:
            split_queries_by_interval: 15m
            max_retries: 5
            cache_results: true
            results_cache:
              cache:
                enabled: true
                expiration: 5m
                max_size_mb: 100

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  dependsOn:
    - kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
