apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.40.0
    # helm:
    #   values: |
    #     loki:
    #       persistence:
    #         enabled: true
    #         size: 5Gi
    #       storage:
    #         type: filesystem
    #       config:
    #         auth_enabled: false


  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  dependsOn:
    - kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
