apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.40.0
    helm:
      values: |
        loki:
          auth_enabled: false

          limits_config:
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            max_cache_freshness_per_query: 10m
            split_queries_by_interval: 15m
            query_timeout: 300s
            volume_enabled: true
            allow_structured_metadata: true # allow structured logs in loki
            
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
            max_concurrent: 2

        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
          resources:
            limits:
              cpu: 3
              memory: 4Gi
            requests:
              cpu: 2
              memory: 2Gi
          extraEnv:
            # Keep a little bit lower than memory limits
            - name: GOMEMLIMIT
              value: 3750MiB

        chunksCache:
          allocatedMemory: 512
          # default is 500MB, with limited memory keep this smaller
          writebackSizeLimit: 10MB

        # Enable minio for storage
        minio:
          enabled: true

        # Zero out replica counts of other deployment modes
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0



  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
