apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.133.0
    helm:
      values: |
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: "0.133.0"
        mode: daemonset
        config:
          receivers:
            filelog:
              include:
                - "/var/log/pods/*/*/*.log"
              start_at: end
          operators:
            - type: json_parser
              parse_from: body
              id: parse_outer
              timestamp:
                parse_from: time
                layout_type: rfc3339

            - type: json_parser
              id: parse_inner
              parse_from: attributes.log
              on_error: drop

            - type: remove
              id: cleanup
              field: attributes.log

          processors:
            k8sattributes:
              auth_type: serviceAccount
              extract:
                metadata:
                  - namespace
                  - pod
                  - container
                labels:
                  - app
                  - app.kubernetes.io/name
            batch: {}

          exporters:
            otlphttp:
              endpoint: "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
              compression: snappy
          service:
            pipelines:
              logs:
                receivers: [filelog]
                processors: [k8sattributes, batch]
                exporters: [otlphttp]

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
