apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.133.0
    helm:
      values: |
        mode: daemonset

        presets:
          logsCollection:
            enabled: true
            includeCollectorLogs: true
          kubeletMetrics:
            enabled: true

        config:
          exporters:
            otlphttp:
              endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        service:
          pipelines:
            logs:
              exporters:
                - otlphttp

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
