apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-rest-api-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/artem-kosenko/demo-github-actions.git
    targetRevision: develop
    path: templates/java-rest-api/charts/java-rest-api
    helm:
      releaseName: java-rest-api
      values: |
        image:
          repository: my-java-rest-api
          tag: latest
        service:
          type: ClusterIP
          port: 8080

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
